### ISSUE TITLE
Contentful does not work with latest Jekyll

### ISSUE THREAD

**Issue by kristian-elder** [contentful/contentful.rb#102]
Not sure if this is an issue with Contentful or Jekyll, but I am unable to use Contentful (via either the Jekyll contentful-data-importer gem or jekyll-contentful) with Jekyll >= 3.1

Attempting to do so results in the server returning a Bad Request and the contentful client attempting to parse the resulting HTML as Json.

Attempting to troubleshoot the request going out via Charles Proxy, it appears that with this setup, the Authorization header is sent twice, one with the value Bearer, one with the actual token, rather than once with Bearer <token>.

**Comment by dlitvakb** [comment]
Hey @kristian-elder,

Could you open a ticket here: https://github.com/contentful/jekyll-contentful-data-import/issues and copy the contents of the `contentful` block in your `_config.yml` file obfuscating the access token and space id?

Please also include Jekyll version, and gem version you are using.

Cheers

PS: Closing issue here as it seems unrelated
