### ISSUE TITLE
what exactly do you pass into client.asset(?)

### ISSUE THREAD

**Issue by sebbean** [contentful/contentful.rb#115]
tried passing the asset class with no luck. do i send the id? the url?

**Comment by dlitvakb** [comment]
Hey @sebbean,

You send the ID, for further documentation: https://github.com/contentful/contentful.rb#assets and http://www.rubydoc.info/gems/contentful/1.2.1/Contentful/Client#asset-instance_method

Cheers

**Comment by sebbean** [comment]
@dlitvakb heyo! yea the readme showed me that that command existed. Just doesnt really say anything about the 'id' being what you pass. just uses some random string 'happycat'.


oo that second link! thanks.
