### ISSUE TITLE
2.0.0 Feedback Appreciated

### ISSUE THREAD

**Issue by dlitvakb** [contentful/contentful.rb#120]
Hello SDK Users,

I would appreciate if you could take a minute to drop your feedback regarding the 2.0.0 version of the SDK currently present on the `master` branch.

It has not yet been released to RubyGems, I'm waiting for some real use feedback.

## Installation

In your `Gemfile` update to use upstream version from this repository:

`gem 'contentful', github: 'contentful/contentful.rb'`

## Breaking Changes

* `DynamicEntry` does no longer exist, now everything inherits from `Entry`
* `CustomResource` and everything related to the former `Resource` are gone
* Former `Resource` related objects, no longer have an instance of `Client` included in them, therefore, things like `Entry#reload`, `Link#resolve`, `Array#next_page` now require a `Client` instance as a parameter
* `#inspect`/`#to_s` for `Resource` related objects has a different and more simplified output format
* `:resource_mapping` only works now for `Entry` and `Asset`, therefore `Array` and `SyncPage` can no longer be overwritten there, this may be changed before release if it's requested.

## Plans going forward

As soon as we consider enough feedback was collected, through this channel or others, we'll proceed on doing the following things:

* Release this SDK 2.0.0 officially
* Update all official tools and integrations that use this gem to the new version

Cheers

**Comment by pmoore** [comment]
Doesn't look like this version is compatible with the current master version of contentful_model, as it requires ~> 0.9 of contentful.rb.  Is there a plan to update contentful_model (and contentful_rails) to a new supporting version?

**Comment by dlitvakb** [comment]
Hey @pmoore, Yes! There is.

We're waiting for some more user feedback before making this release official.

After that's done, focus will shift onto updating all libraries and integrations using this gem to use the new simplified gem.

Cheers

**Comment by sebbean** [comment]
Caching is my number one priority at the moment as we're using contentful within an API response so we're unable to use rails russian doll caching.

**Comment by dlitvakb** [comment]
Hey @sebbean can you share more of your issue? I'm going to add today a way to customize depth of the include resolution tree, to greatly increase speed of caching.

Cheers

**Comment by sebbean** [comment]
So i'm tightly integrating contentful models with active record models that power a pure API.

Any caching mentioned in these gems seems to only happen within the rails templates _after_ the initial call to contentful is made.

The api is hit quite a bit and i'm weary of blowing through our api limits if i'm unable to wrangle the responses into a proper cache. Especially considering we have the webhooks all setup properly.

this is inside our 'Ingredient' ActiveModel subclass:

```
    def content
      @content ||= Gravy::IngredientInfo.find_by(slug: slug).load.try(:first)
    end
```

Would be happy to talk through in a hangout or chat if it's easier to convey.

-sb

**Comment by dlitvakb** [comment]
2.0.0 has been released! 🎉 

Closing this issue now
