### ISSUE TITLE
Add File/Tempfile capabilities to Contentful::File

### ISSUE THREAD

**Issue by andyentity** [contentful/contentful.rb#122]
Hello people,

good SDK so far.
I am currently working with assets such as Rich Text Documents which I am downloading in order to process them afterwards.

Since the `Contentful::Array` behaves like a proper Enumerable it could be assumed that `Contentful::File` might also be used like a normal `File`, that is, you can `open` it (read-only) and then `read` from it etc. and `unlink` it again afterwards. Right now the class is only a wrapper for the various fields of the model.

Since it is not such an unusual use case I think it would be a good addition to be able to have the `Contentful::File` class conveniently download and serve you the asset as a real [File](https://ruby-doc.org/core-2.2.0/File.html)/[Tempfile](http://ruby-doc.org/stdlib-2.2.0/libdoc/tempfile/rdoc/Tempfile.html) if you need to.

**Comment by dlitvakb** [comment]
Hey @andyentity,

Thanks for the request, but I'll have to decline it, as this request would require something like [OpenURI](https://ruby-doc.org/stdlib-2.2.0/libdoc/open-uri/rdoc/OpenURI.html) which is considered insecure.

If you know of a safe alternative we can use, feel free to suggest it.

Cheers
