### ISSUE TITLE
ability to upload asset

### ISSUE THREAD

**Issue by sebbean** [contentful/contentful.rb#123]
possible in CMA but doesnt seem to be in this gem

**Comment by dlitvakb** [comment]
Hey @sebbean,

I'm going to be implementing this during the next week. Stay tuned for updates

Cheers

**Comment by sebbean** [comment]
aweeeeeeeee yeaaaaaa.

**Comment by dlitvakb** [comment]
I'm starting development on this right now 😄 

I'll let you know once the PR is created

Cheers

**Comment by sebbean** [comment]
need to migrate a buunch of images from old system to contentful. curious if it makes sense to make a rake task to just "get er done" or hold off for a few days and test out this new feature of yours.

related: if you want me to test out your progress id love to be your guinea pig 😄

**Comment by dlitvakb** [comment]
Hold off for a few days, you'll be very pleased :D (or if you want to try it out with python, you can do it right now! https://contentful.github.io/contentful-management.py/#uploads

**Comment by dlitvakb** [comment]
This is still being worked on, had a few issues with the HTTP layer of the management gem. Working on solving them, but right now focusing on a different issue to get my mind a bit refreshed.

I'll update you when this is done.

Cheers

**Comment by sebbean** [comment]
thanks bud! lmk if you want me to look anything over. i've had a bit of ssl esperience here and there

**Comment by dlitvakb** [comment]
Hey @sebbean,

Issues have been found and fixed, Upload API is now ready for merge 😄  just waiting on review.

Cheers
