### ISSUE TITLE
Contentful::Array doesn't marshal/unmarshal properly

### ISSUE THREAD

**Issue by plexus** [contentful/contentful.rb#132]
`Contentful::Array` inherits from `Contentful::BaseResource`, which implements custom `marshal`/`unmarshal` hooks.

Array uses several instance variables not present in its superclass, so after unmarshalling you end up with a broken instance.

I'm working around it now with this monkey patch, but would be great if this could be addressed.

Thanks!

``` ruby
module Contentful
  class Array
    def marshal_dump
      [raw, @endpoint]
    end

    def marshal_load(input)
      super(input[0])
      @endpoint = input[1]
      @total = item.fetch('total', nil)
      @limit = item.fetch('limit', nil)
      @skip = item.fetch('skip', nil)
      @items = item.fetch('items', [])
    end
  end
end
```

**Comment by dlitvakb** [comment]
Hey @plexus,

Thanks for noticing this, I'll be taking care of it within the next 2 weeks.

Cheers

**Comment by plexus** [comment]
Great, thanks a lot! Just FYI in the end we went with this patch, it plays better with the changes to marshaling in the latest version of contentful.rb

``` ruby
class Contentful::Array
  def marshal_dump
    super.merge(endpoint: @endpoint)
  end

  def marshal_load(raw_object)
    super
    @endpoint = raw_object[:endpoint]
    @total = @raw.fetch("total", nil)
    @limit = @raw.fetch("limit", nil)
    @skip = @raw.fetch("skip", nil)
    @items = @raw.fetch("items", [])
  end
end
```

**Comment by dlitvakb** [comment]
Hey @plexus,

The fix came way earlier :) Just looking for a reviewer from my team to merge, thank you very much for the help.

Cheers
