### ISSUE TITLE
How to query by content_type and fields name?

### ISSUE THREAD

**Issue by FayeFang** [contentful/contentful.rb#141]
I have read through the API documentation and cannot find a good way to query.

I have tried 
`client.entries('content_type' => 'abc', 'fields.a' => 'abc') ` and got error.

In addition, what if the field is an entry of another content type?

Help is much appreciated!

**Comment by dlitvakb** [comment]
Hey @FayeFang,

Your way should work, a shorter version is:

```ruby
client.entries(content_type: 'abc', 'fields.a' => 'abc')
```

Could you share what the error is?

Cheers

**Comment by FayeFang** [comment]
Yep yep. Trying to query by field title and title field do exist.

```
[5] pry(#<ContentfulController>)> @blogs = client.entries(content_type: 'pages').first.fields[:title]
=> "Three Signs You Should Refinance Your Auto Loan"
[6] pry(#<ContentfulController>)> @blogs = client.entries(content_type: 'pages', 'fields[:title]' => 'abc')
Contentful::BadRequest: The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field.
from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contentful-2.1.0/lib/contentful/client.rb:321:in `fail_response'
[7] pry(#<ContentfulController>)> @blogs = client.entries(content_type: 'pages', 'fields[:title]' => 'abc')
Contentful::BadRequest: The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field.
from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contentful-2.1.0/lib/contentful/client.rb:321:in `fail_response'
[8] pry(#<ContentfulController>)> @blogs = client.entries(content_type: 'pages', 'fields.title' => 'abc')
Contentful::BadRequest: The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field.
from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contentful-2.1.0/lib/contentful/client.rb:321:in `fail_response'
[9] pry(#<ContentfulController>)> @blogs = client.entries(content_type: 'pages', 'fields.title': 'abc')
Contentful::BadRequest: The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field.
from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/contentful-2.1.0/lib/contentful/client.rb:321:in `fail_response'
```

**Comment by FayeFang** [comment]
Also, how should I query if the field is an Entry of another content type?

**Comment by dlitvakb** [comment]
Hey @FayeFang,

Can you open a support request and request for my help? We can move forward from there.

As for the relational query, you can take a look here: https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/search-on-references, there is an example using the Ruby SDK.

Cheers

**Comment by FayeFang** [comment]
Cool thanks! request submitted.

**Comment by thisismydesign** [comment]
I'm trying to figure out the same, would be helpful if you posted the outcome here.

**Comment by thisismydesign** [comment]
Alright, so based on the above example assuming you have
- a type called `event`
- a reference called `category`
- the reference is of type `event_category`

To search by ID:

`query = {content_type: 'event', 'fields.category.sys.contentType.sys.id' => 'event_category', 'fields.category.sys.id' => '<id>'}`

To search by some field:

`query = {content_type: 'event', 'fields.category.sys.contentType.sys.id' => 'event_category', 'fields.category.fields.someField' => '<value>'}`

See also: https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/search-on-references/search-on-references/console/ruby
