### ISSUE TITLE
[Feature Request] Disable snake_case

### ISSUE THREAD

**Issue by colepatrickturner** [contentful/contentful.rb#142]
I'm working with Contentful -> Ruby -> JavaScript and I've designed my schema according to how the editor encourages which is camelCase.

The v2 Ruby client automatically rewrites all the keys as snake_case. I understand why this is done for the sake of Ruby convention but when working with an API/schema - one would expect the format to be consistent across languages. 

Can we please have an option that disables `snakify` and preserves the original API in its pure casing?

**Comment by dlitvakb** [comment]
Sounds like something that could be implemented.

I'm going on vacation for the next few weeks, but I'll add it to our backlog for when I'm back.

Cheers

**Comment by colepatrickturner** [comment]
Thank you 👍

**Comment by monkseal** [comment]
👍  would love to have this option.

**Comment by johnnyiller** [comment]
👍  Agreed

**Comment by dlitvakb** [comment]
Hey there,

I've just finished a bunch of feature additions for the CMA SDK which will be released on monday.

I'll talk with my PM about prioritizing this feature.

You should be expecting it within this month.

Cheers

**Comment by monkseal** [comment]
@dlitvakb Thanks! 🎉 🍇 🏄

**Comment by dlitvakb** [comment]
This has been merged to master.

That said, this won't be released for a few weeks until I add a few other improvements.

Cheers

**Comment by dlitvakb** [comment]
This has been released in version `2.2.0`.

Cheers
