### ISSUE TITLE
Asset Retrieval 404

### ISSUE THREAD

**Issue by joshiefishbein** [contentful/contentful.rb#147]
I am attempting to retrieve a specific asset using `@client.asset(<asset_id>)` however it returns a 404:

    Contentful::NotFound: The resource could not be found. 
    from /Users/joshiefishbein/.rvm/gems/ruby-2.3.1/gems/contentful-2.1.1/lib/contentful/client.rb:321:in `fail_response'

When I pry open `@client.assets` I see the asset there in the array when I map it. I copy and paste that individual ID into `@client.asset` as a string and it doesn't work.

I am only having this problem with a recently uploaded image that was added to the Media folder using the Contentful Management file method. I published it manually and it shows up in the Media folder normally, just like every other image. But I can't retrieve it.

What's happening here?

**Comment by dlitvakb** [comment]
Hey @joshiefishbein,

Can you open a support request at https://support.contentful.com/hc/en-us ?

There we can better help you with your issue.

Cheers

**Comment by grumpyoldman-io** [comment]
Heya, I'm also running in to this problem. Perhaps you can share the solution here in public so others can solve it as well. Thanks!

**Comment by joshiefishbein** [comment]
@grumpyoldman-io a few different things were causing this for me:

1. I made the request for the `link` before it propagated throughout the Contentful CDN network. So when I first hit a 404 for the entry (after immediately refreshing) the client cached that 404 response. As soon as I modified the query it started working again because it was technically a new, clean query to fetch.

2. The CDN took longer to update than Contentful normally quotes updates to take.

3. Make sure your query allows for the include depth you are targeting. Use the `include` argument in your query to ensure your `link` can actually be retrieved.

**Comment by dlitvakb** [comment]
Hey @grumpyoldman-io,

Could you also send a support request?

This is not an SDK related issue, and should be dealt with in a case by case basis.

The above issue was a caching issue, they requested the asset in an extremely short window between a cache flush and the cache population, and the cache stored the 404 response.

Easiest way to solving it is to publish anything either through the WebApp or the CMA, wait a few seconds, and try again. You can also send additional parameters such as `client.asset(asset_id, t: 'foo')`, this will create a new entry in the cache, for that query string, you can use that until you refresh the cache by publishing.

Hope this helps,

Cheers

**Comment by dlitvakb** [comment]
Yup, exactly as @joshiefishbein said.

**Comment by grumpyoldman-io** [comment]
thanks! I do fire a request immediately after getting a webhook, I will try adding a small delay and other solutions. If that doesn't work I'll contact support.

**Comment by dlitvakb** [comment]
Hey @grumpyoldman-io,

There's usually about a 3 to 5 second delay between the webhook is triggered and the resource is available.
This is something that may be increased in case that your space is exceeding the tens of thousands of entries.

Cheers
