### ISSUE TITLE
Empty Date Time field causes TypeError 

### ISSUE THREAD

**Issue by natsumi** [contentful/contentful.rb#148]
An empty datefield will cause a typeerror.  Same issue as #18

**Comment by dlitvakb** [comment]
Hey @natsumi,

Could you please let me know which version of the gem are you using?

Also, do you have a code snippet to reproduce this issue?

Cheers

**Comment by natsumi** [comment]
I'm using version 2.1.0 but the issue persists even with 2.1.3.  I'm just running a basic filter:
```ruby
      filter = {
        skip: skip,
        limit: limit,
        order: 'fields.publishDateTime',
      }
```
However, one of the entries come back with a nil date time field (which is not required) and it causes line 62 in lib/contentful/coercions.rb to throw a TypeError because value is now nil.

**Comment by dlitvakb** [comment]
Hey @natsumi,

This looks like it may indeed be a bug,

I'll take a look into it and check what may be happening.

Cheers

**Comment by jacobduursma** [comment]
Hey @dlitvakb 

Not sure if you had time to fix yet? Looks like the bug is still there, just been having the same issue (version 2.3.0).

Cheers
