### ISSUE TITLE
No count method, nor a way to paginate requests

### ISSUE THREAD

**Issue by lucke84** [contentful/contentful.rb#153]
It seems that by default there's a limit applied to each query (which makes sense for performance reasons, although it doesn't seem to be documented anywhere?). 

At the same time, I would expect to have:
- a method to get a count of how many items (for a given query, for instance a certain content type) are currently present in a space
- a way to paginate the requests (for a given query)

I couldn't find any of those in the doc or the code, am I missing anything here? 😄 

Otherwise, what's the expected way of retrieving plenty of items in a performant way?

**Comment by dlitvakb** [comment]
Hey @lucke84,

All collection endpoints accept a `limit` and `offset` parameter, which allow you to control the amount of resources returned, it's recommended to use the `order` parameter if you're paginating your content. You can find more info here: https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/collection-resources-and-pagination

Also, `Contentful::Array` objects, which are returned from said collection endpoints, have the `total`, `size` and `skip`. Which reflect the total amount of resources for that collection, the size of the current collection and the amount of resources skipped (offset).

Hope this explains better how it works,

Cheers

**Comment by lucke84** [comment]
Hey @dlitvakb, thanks for your reply! 

I have to admit I mostly looked into the `examples` folder of this repo. I understand how it works now, I'd recommend to add some pointers for people that like me will look first in the codebase; a link in the README or another example query for the usage of pagination would be very useful.

**Comment by dlitvakb** [comment]
Hey @dagumak,

The easiest way to paginate is to use something like follows:

```ruby
def all_entries(cda_query, per_page = 100)
  all = []
  query = cda_query.clone
  query[:order] = 'sys.createdAt' unless query.key?(:order)
  num_entries = client.entries(limit: 1).total

  ((num_entries / per_page) + 1).times do |i|
    query[:limit] = per_page
    query[:skip] = i * per_page
    page = client.entries(query)
    page.each { |entry| all << entry }
  end

  all
end
```

Hope this helps,

Cheers
