### ISSUE TITLE
Documentation on site is different

### ISSUE THREAD

**Issue by mmplisskin** [contentful/contentful.rb#155]
https://www.contentful.com/developers/docs/references/content-management-api/#/reference/entries/entries-collection/get-all-entries-of-a-space/console/ruby

A lot of these docs are different, it makes this sdk difficult to use.

**Comment by dlitvakb** [comment]
This SDK is the Delivery SDK, you're looking for the docs of the Management SDK, which can be found in github.com/contentful/contentful-management.rb
