### ISSUE TITLE
draft or missing contents are still being pulled in

### ISSUE THREAD

**Issue by mickeyren** [contentful/contentful.rb#157]
when a content is for example missing:

![2018-01-10 at 6 34 pm](https://user-images.githubusercontent.com/175045/34768139-f8c7f468-f634-11e7-81c8-477ec37efe1b.jpg)

or in draft mode, but they are associated to another model that is being fetched, these associated contents are also being included and end up as just being`Contentful::Link`.

Is this the desired behaviour? I would imagine that if the content has gone missing, or especially if they are in draft, they shouldn't be included when pulling content from the production cdn.

**Comment by monkseal** [comment]
Yeah, it would be nice if the link had something like `unpublished?`...

**Comment by dlitvakb** [comment]
This is something we're looking into adding, though it relies on something that's undocumented. So we're looking for the best approach to do this.

Cheers

**Comment by dlitvakb** [comment]
Update on this,

This will be added next week, and it will be the default behaviour of the SDK.

Cheers
