### ISSUE TITLE
What is the recommended way to present an entry along with all its linked fields?

### ISSUE THREAD

**Issue by mmwtsn** [contentful/contentful.rb#159]
Let's say I have a content type called "book" that has a title, a published date, and a link to an author entry. Is there a way to present the entry and all linked entries as a hash or as JSON?

Basically, I want to do the following:

```ruby
entries = client.entries(content_type: "book")
entry = entries.first
entry.to_h
=> {:title => "The Sun Also Rises",
:author => {:first => "Ernest", :last => "Hemingway"},
:published_date => Fri, 22 Oct 1926 12:00:00 -0500}
```

Calling `entry.fields` gives you the fields but does not resolve the linked entries automatically:

```ruby
entry.fields
=> {:title => "The Sun Also Rises",
:author => <Contentful::Entry[author] id="TCNlAvmW4uYQkGYoiSqac">,
:published_date => Fri, 22 Oct 1926 12:00:00 -0500}
```

If you call `entry.to_json` or `entry.as_json` you get an absolutely massive response (one of our smaller content types returns over 200,000 lines of JSON if you pretty print the result). I feel like I'm missing something obvious. Is there a way to do this without iterating over the fields myself?

**Comment by dlitvakb** [comment]
Hey @mmwtsn,

You can do this with `#raw`.

Hope this helps,

Cheers
