### ISSUE TITLE
Unpublished link drafts should be filtered from content delivery api responses

### ISSUE THREAD

**Issue by incraigulous** [contentful/contentful.rb#174]
if a content manager ignores the warning about publishing and item with linked drafts, and published anyway, the draft still shows up in the content delivery api. I was checking for `item.content_type.id`, and it took down a page on our site because that didn't even exist on the draft item that made it into our results. 

I would think the expected functionality would be that unpublished items never show up in the content delivery api. Is this a bug? If not, is there a way to filter them out?

**Comment by dlitvakb** [comment]
Hey @incraigulous,

Which version are you using? This has been automatically done since version [2.5.0](https://github.com/contentful/contentful.rb/blob/master/CHANGELOG.md#250).

Cheers

**Comment by incraigulous** [comment]
Looks like we're using 2.8.0.

**Comment by dlitvakb** [comment]
Hey @incraigulous,

This indeed seems like there may be a bug.

Could you open a support request at https://support.contentful.com and provide the Delivery Key and Space ID, so that our support engineers can look further into your specific case?

Cheers

**Comment by incraigulous** [comment]
Sure thing @dlitvakb! I'll make that support ticket tonight!
