### ISSUE TITLE
Gem strips markdown from text fields

### ISSUE THREAD

**Issue by mrispoli24** [contentful/contentful.rb#182]
I'm finding that this gem is stripping out the markdown from long text fields. Is there a way for this gem to parse markdown to html for long text fields? I don't see this as an option in the documentation.

**Comment by mrispoli24** [comment]
I installed red carpet as a separate gem but just wanted to still inquire if there was any kind of option for this in the Contentful gem. If not it might be helpful to just add this as a note to the documentation that will be needed.

**Comment by dlitvakb** [comment]
Hey @mrispoli24,

This gem doesn't alter the content of long text fields, say you write something in the Markdown editor, the gem will output the underlying text representation of that markdown, for example:

```md
# some title

* a list item

some text
```

RedCarpet (has a little different syntax for code blocks) or CommonMarker (a standardised set of markdown) are what we often recommend to use along side the SDK for doing the markdown rendering.

You can see an example usage of CommonMarker in our [Ruby Example App](https://the-example-app-rb.herokuapp.com/) here: https://github.com/contentful/the-example-app.rb/blob/master/views/_moduleCopy.slim#L7

Hope this helps,

Cheers
