### ISSUE TITLE
Incorrect default message on ServiceUnavailable error class

### ISSUE THREAD

**Issue by rezonant** [contentful/contentful.rb#183]
https://github.com/contentful/contentful.rb/blob/02556988aabff49962118df44feaa5b1f79043bc/lib/contentful/error.rb#L189

**Comment by dlitvakb** [comment]
Hey @rezonant,

Sorry this took so long, the issue got lost on my backlog, creating a patch release for it in a moment, should be released in the next hour or so.

Cheers
