### ISSUE TITLE
Allow configuring HTTP timeouts

### ISSUE THREAD

**Issue by clupprich** [contentful/contentful.rb#186]
Is anybody already working on allowing to configure HTTP timeouts for the `Client`? [`http` allows you to do that](https://github.com/httprb/http/wiki/Timeouts), but it's not exposed in the configuration options of the client.

**Comment by dlitvakb** [comment]
Hey @clupprich,

Haven't considered adding this yet, there is a timeout configuration for retries on 429 failures.

Could you explain a bit further on why would you need this feature?

Cheers

**Comment by clupprich** [comment]
Hej @dlitvakb,
With the service disruption last week, we noticed that certain requests did go through to your CDN, but they took a _very_ long time to return a response. In our situation it would have been better to fail early and set the HTTP read timeout to e.g. 5 seconds (instead of the default 60 seconds). I guess this woulnd't only be interesting for `read_timeout`, but also `open_timeout`? Might even

**Comment by elhu** [comment]
Hi!

We've just experienced the exact issue that @clupprich describes.
Is there any news on plans to allow timeouts to be configured?

**Comment by dlitvakb** [comment]
Hey @clupprich and @elhu,

I'll take a look into this - and try to get it into the SDK as soon as I can.

Cheers

**Comment by elhu** [comment]
@dlitvakb I gave it a quick try: https://github.com/contentful/contentful.rb/pull/196

**Comment by teemutammela** [comment]
In the mean time, is there some best practice - or failing that, an ugly hack 😆  - for dealing with Delivery API failures? Preferably a rescue after Delivery API fails to delivery content within X amount of seconds.

**Comment by elhu** [comment]
You can always wrap the call in a https://ruby-doc.org/stdlib-2.2.0/libdoc/timeout/rdoc/Timeout.html block, but it's a very brutal way of handling this kind of things and can lead to some nasty surprises.

**Comment by teemutammela** [comment]
I wonder if [rack-timeout](https://github.com/heroku/rack-timeout) would be of any use. My application is based on Sinatra.

**Comment by elhu** [comment]
@teemutammela if I read that correctly, this is used to terminate a request to your application, not a request your application makes to Contentful.

Depending on what you're trying to achieve, it might work as well.

**Comment by elhu** [comment]
@dlitvakb any news regarding a fix to this issue? Did you get a chance to check out #196 ?
