### ISSUE TITLE
use_camel_case: true causes nil reference error when accessing empty fields

### ISSUE THREAD

**Issue by boxbinary** [contentful/contentful.rb#203]
The following line references `content_type` but if you have created the client with `use_camel_case: true`, the `keys` of `sys` have been instantiated using camelCase (e.g. it should be `contentType` in this case), and a nil reference error is thrown trying to access `sys[:content_type].id`

https://github.com/contentful/contentful.rb/blob/487d04430cc2b2ea70580e446e318a4d59ed1417/lib/contentful/entry.rb#L108

This makes it impossible to use camel casing while also referencing fields that might be empty.

**Comment by dlitvakb** [comment]
The fix has been released in version `2.13.1`.

Cheers
