### ISSUE TITLE
Recommendations for optimal Memory Usage?

### ISSUE THREAD

**Issue by 0xStarcat** [contentful/contentful.rb#209]
Hi, I recently upgraded my gem 2 major versions from `0.7.0` to `2.13.3`  and I'm seeing an almost x3 increase in memory usage (from 0.5 GB to 1.5GB - 2GB). 

I'm using this gem in a Ruby on Rails app and it includes caching of content with MemCachier. 

Here's the delivery client config: 

```
def delivery_client_params
        {
          access_token:                 Rails.configuration.x.contentful.access_token,
          space:                        Rails.configuration.x.contentful.space,
          log_level:                    Logger::INFO,
          raw_mode:                     false,
          entry_mapping:                entry_mapping,
          gzip_encoded:                 true,
          raise_for_empty_fields:       false,
          dynamic_entries:              :auto,
          reuse_entries:                true,
          max_include_resolution_depth: 5,
        }
```

Do you have any recommendations for what we can tweak to get back to our originally low memory usage? 

I don't know if this is relevant, but we have models which contain circular references, which we're manually resolving the links for (they are saved as Contentful::Link in cache). Could that result in a memory leak maybe?

**Comment by dlitvakb** [comment]
Hey @0xStarcat ,

Circular references are the only reason why this version of the gem would be consuming more memory, that said, if you're using `reuse_entries`, and limit the max include resolution depth, this should be pretty much mitigated.

Please make sure that your own internal mechanism for entry resolution is not consuming extra resources and that your queries are using includes up to the level required and not additional levels, which may turn into being less memory efficient queries.

Hope this helps,

Cheers

**Comment by 0xStarcat** [comment]
Thanks for the reply! 

I have a sneaking suspicion is may have to do with `reuse_entries` maybe? 

In the README, it mentions that I should not use `reuse_entries` if I'm using Rails Caching. Can you talk a little bit more about why that is? 

What I'm noticing is that with `reuse_entries` set to `false`, and `max_resolution depth` set to 3, my app does NOT need to resolve the circular references.

However with `reuse_entries` set to `true` and `max_resolution_depth` set to 5, my app does need to resolve the references.

**Comment by dlitvakb** [comment]
Hey @0xStarcat ,

What happens is that in the process of `unmarshaling` the entries from cache, when using `reuse_entries` it may not be able to find the related entries, due to these potentially having circular references, if you content were mostly unique entries, or just reused entries but without circular references, this should not be a problem.

What I would recommend, in your particular case is to reduce the `max_include_resolution_depth` to the minimum necessary for your pages to render properly, since this will be the most important factor in keeping your memory consumption low, and then try `reuse_entries` both on and off and check how caching behaves for each case, if it works properly with `reuse_entries` set to true, then that should be better. But this is very dependant on how your content is structured.

Hope this helps,

Cheers

**Comment by 0xStarcat** [comment]
I'll implement your recommendation to keep the API `includes` parameters below the `max_resolution_depth` and I'm going to turn off `reuse_entries` while lowering `max_include_resolution_depth` to the number that works best for my app. 

Thanks for your help! I'll report the results later today

**Comment by 0xStarcat** [comment]
The newest config works for a time, but unfortunately it appears like our app or the gem has a memory leak somewhere... memory usage slowly doubles over the course of a few hours. This didn't happen until after we upgraded the gem. 

Trying to cross off the list of potential causes, I managed to "close the gaps" and cache all of our templates, so link resolution is no longer occurring regularly after the first cache.

If you want to close this, feel free. I don't know what other information I can provide to troubleshoot. I'll reply back if I discover the issue.

Latest config (reuse entries set to false and max resolution lowered to 3):
```
params  = {
          access_token:                 Rails.configuration.x.contentful.access_token,
          space:                        Rails.configuration.x.contentful.space,
          log_level:                    Logger::INFO,
          raw_mode:                     false,
          entry_mapping:                entry_mapping,
          gzip_encoded:                 true,
          raise_for_empty_fields:       false,
          dynamic_entries:              :auto,
          reuse_entries:                false,
          max_include_resolution_depth: 3,

        }
```

**Comment by 0xStarcat** [comment]
I'm not sure it's not possible to determine if this is a common [Rails / Puma / Heroku](https://github.com/puma/puma/issues/1047) issue, or an issue with another gem we upgraded at the same time, or what. 

Closing

**Comment by 0xStarcat** [comment]
We configured herkou with `jemalloc` and memory usage improved. Thanks for your insight & help with the gem config!

**Comment by antwonlee** [comment]
@0xStarcat Did switching to `jemalloc` solved your issue?  I am having too much memory allocation when I am pulling all the entries from Contentful.
