### ISSUE TITLE
Warning: URI.escape is obsolete (Ruby 2.7.0)

### ISSUE THREAD

**Issue by teemutammela** [contentful/contentful.rb#217]
Apparent `URI.escape` is obsolete in Ruby 2.7.0, so the following warning is shown whenever a request is made to Delivery API.

`/Users/username/.rvm/gems/ruby-2.7.0/gems/contentful-2.15.2/lib/contentful/request.rb:16: warning: URI.escape is obsolete`

**Comment by Amith-catadoe** [comment]
> Apparent `URI.escape` is obsolete in Ruby 2.7.0, so the following warning is shown whenever a request is made to Delivery API.
> 
> `/Users/username/.rvm/gems/ruby-2.7.0/gems/contentful-2.15.2/lib/contentful/request.rb:16: warning: URI.escape is obsolete`

Hi there,
I too have the same problem.
Did you find any solutions to fix this problem?

**Comment by teemutammela** [comment]
Hi @Amith-catadoe . Not a solution per se. At the moment I'm just sticking to Ruby 2.6.5.

**Comment by dlitvakb** [comment]
@teemutammela @Amith-catadoe Heya there, I think I've found a possible fix. Tomorrow I'll be testing this and pushing a new version if it works.

Cheers

**Comment by teemutammela** [comment]
@dlitvakb Awesome, thanks!

**Comment by dlitvakb** [comment]
Hey @teemutammela @Amith-catadoe 

A fix has been now released on version `2.15.3`.

Cheers

**Comment by teemutammela** [comment]
@dlitvakb Confirmed. The fix in `2.15.3` got rid of the warning. Thanks!  👍

**Comment by Amith-catadoe** [comment]
@dlitvakb Thank you very much!!
