### ISSUE TITLE
Bug in hydration with circular references?

### ISSUE THREAD

**Issue by MGPalmer** [contentful/contentful.rb#225]
Hello!

I think I may have found a pretty subtle bug in the "hydration" code, which has taken me a long time to drill down to now X) Let me explain the setup:

Among other content_types, we have so called "Winner" and "News" (also called Articles) entries. News have a rich_text field that has elaborate text and inline images. A winner can link to many news, and sometimes news in turn link to Winners. This is usually no problem, but in a specific call we get a single winner with include 2, which sometimes means that there are news which have the same winner on it again. If that happens, everything looks fine at first, but some of the images (assets) in rich_image entries in rich_text of the news will not be hydrated, crashing our rendering, as it expects to get the urls of assets directly, but will encounter Link objects.

What's making this more head-scratching is that this only occurs when the news of the winner are in a specific order - when re-ordered, the hydration works, even though no other data is changed (I'm attaching two samples, they are the different orders of the same winner-with-two-news, and also the content types of news and winners).

This also doesn't occur when setting reuse_entries to true.

Also, the include option on the call, or max_include_resolution_depth have no effect on the hydration issue (i.e. I tried it with much higher values than 2/4, and it has no effect).

Here's more info, let me know if there is more needed:

gem version 2.15.3

relevant settings:

```

{
  entry_mapping: {
  'news' => Content::News::Article,
  'author' => Content::News::Author,
  'category' => Content::News::Category,
  'milestone' => Content::News::Highlight,
  'jobs' => Content::News::Job,
  'pages' => Content::News::Page,
  'press_release' => Content::News::PressRelease,
  'member' => Content::News::TeamMember,
  'media_coverage_item' => Content::News::MediaCoverageItem,
  'profile_message_to_all_users' => Content::News::UserMessage,
  'simple_data_record' => Content::News::SimpleDataRecord,
  'winner' => Content::News::Winner,
  'ad_hoc_campaign' => Content::AdHoc::Campaign,
  'notification' => Content::AdHoc::Notification,
  'rich_image' => Content::News::Elements::RichImage,
  'button' => Content::News::Elements::Button,
  'youtube_video' => Content::News::Elements::YoutubeVideo,
  'html_code' => Content::News::Elements::HtmlCode,
  'pilot_member' => Content::Pilot::TeamMember
},
  reuse_entries: false,
  dynamic_entries: :auto,
  max_include_resolution_depth: 4,
  raise_for_empty_fields: false,
}

```

**Comment by MGPalmer** [comment]
Working winner: https://pastebin.com/fnuUUG25
Working winner: https://pastebin.com/CpQuXyP5
Content types: https://pastebin.com/UV21wFFx

**Comment by floriank** [comment]
Hey!

Thanks for reporting - also sorry for the delayed response. I will try and reproduce this and get back to you asap.

**Comment by floriank** [comment]
> Working winner: https://pastebin.com/CpQuXyP5

@MGPalmer I assume this is the broken data ? :wink:

**Comment by MGPalmer** [comment]
@floriank Ah yes, my bad. Thanks for looking at this, much appreciated!

**Comment by floriank** [comment]
mmh, 

so far i could not reproduce the behaviour in a similar setup (using circular references with entries and assets).

do you have a demo project somewhere were it breaks?

**Comment by MGPalmer** [comment]
@floriank yeah it seems to happen only in some unfortunate combinations. We can reproduce it reliably in our project but that's not public unfortunately. Hmm apart from the content model and data I linked to above, what you you need to reproduce? Our subclasses of Content::Base used in the entry_mapping don't do anything special.

**Comment by floriank** [comment]
Well, ideally I could debug in your project locally, but that's not in the cards, so I'd need the same data setup ideally - which rebuilding manually will cost me a lot of time :(

**Comment by MGPalmer** [comment]
@floriank I can try to hack something together but I'm pretty busy at the moment, so it would take me some days.
But here's a wild idea, since we're both in Berlin, we could meet and I could just show you the issue? Send me a PM for contact if that's an option for you :)

**Comment by floriank** [comment]
I would not meet up physically during corona, but a video call might be in the cards.

Pretty busy over here at contentful myself, I'll check my calendar.

**Comment by MGPalmer** [comment]
@floriank I'm still up for that call, btw ;)

**Comment by floriank** [comment]
Sure, I sent you an email earlier - I assumed you were busy.

**Comment by MGPalmer** [comment]
@floriank Hmm no idea where that got lost, sorry. Can you try again, please?

**Comment by floriank** [comment]
Investigating this, I've created a branch over at my fork with a [fake `vcr_cassette`](https://github.com/floriank/contentful.rb/blob/fix/issue-225/spec/fixtures/vcr_cassettes/entries/issue_225_broken.yml) simulating your "broken" response. 

I also included a spec to verify the behaviour you were describing - see https://github.com/floriank/contentful.rb/blob/fix/issue-225/spec/entry_spec.rb#L788.

Question for me would be what exactly I could set as expectations to verify that the bug occurs consistently:

```ruby
it 'encounters a bug in hydration' do
  vcr('entries/issue_225_broken') do
      news = winner.news
      # look for failing images in them rich text of the news
      # e.g. smth like winner.news.map(&:rich_text) [...] ?
  end
end
```

@MGPalmer Could you quickly help me out here and give me the failing test code you have again? Thanks!

**Comment by MGPalmer** [comment]
@floriank We're doing this:

```
    context 'with an asset in a rich_image in a rich_text of an Article of a Winner' do
      shared_examples_for 'a renderer' do
        let(:rich_text) { article.rich_text }
        let(:rendered_text) do
          RichTextRenderer::Renderer.new(
            'embedded-entry-block' => described_class
          ).render(rich_text)
        end
        let(:image_url) do
          '//images.ctfassets.net/thownz9vc5w0/4UKPR89IKskq8WCwa0GYeQ/'\
          'f7a43b1f7cb86653c543cfa12ade5ad1/Bildschirmfoto_2017-10-24_um_12.59.32.png'
        end

        it 'loads correct article' do
          expect(article.id).to eq('vGienFOrtIM8G8IAo2uuA')
        end

        it 'hydrates rich_image node correctly' do
          expect(rich_text['content'][13]['data']['target'].image.url).to eq(image_url)
        end

        it 'renders text successfully' do
          expect(rendered_text).to include(image_url)
        end
      end

      context "with articles in 'normal' order" do
        before { stub_contentful_api('news/working_winner_bi_34', :winner) }

        let(:article) { Content::News::Winner.find_with_news(34).news.first }

        it_behaves_like 'a renderer'
      end

      context 'with articles in reverse order' do
        before { stub_contentful_api('news/broken_winner_bi_34', :winner) }

        let(:article) { Content::News::Winner.find_with_news(34).news.last }

        # Without "reuse_entries: true" in Content::Base, this causes the
        # "undefined method `url' for <Contentful::Link id='4UKPR89IKskq8WCwa0GYeQ'>:Contentful::Link"
        # error.
        it_behaves_like 'a renderer'
      end
    end
  end
```

**Comment by floriank** [comment]
I rebuilt the relevant parts into a test setup - see https://github.com/floriank/contentful.rb/blob/fix/issue-225/spec/entry_spec.rb#L836.

One issue i face is that neither `rich_image` gets hydrated here, I face a `Link` (a hash actually when evaluating `rich_text['content'][13]['data']['target'].image`.

**Comment by floriank** [comment]
I successfully build a version that fails like your response: See https://github.com/floriank/contentful.rb/blob/fix/issue-225/spec/entry_spec.rb#L788.

Turns out this behaviour is at least _odd_. Paging @dlitvakb for visibility.

**Comment by MGPalmer** [comment]
@floriank thanks for staying on it, and also for the new release, I'm working on integrating it and removing our hacks :)

**Comment by MGPalmer** [comment]
Oho, just found this again - I think this got fixed, or we had a workaround after all. In any case, not a problem anymore so I'll close :) Thanks!
