### ISSUE TITLE
Method for boolean fields are missing when not set

### ISSUE THREAD

**Issue by toadle** [contentful/contentful.rb#227]
Hey guys, 

I don't know if this is intended behaviour: We have several boolean-fields in our Content-models. 
E.g. a `display_toc` oder `sponsored_article`-property.

Of course the editorial staff only edits these fields, if need which produces a lot of empty values in our objects. 

Now I noticed that when the field is empty, the `method` is also missing in the `Contentful::Entry` even though it is present in the Content-Model. 

When the field is set the method appears.

Shouldn't the method always be present?

**Comment by toadle** [comment]
I just noticed that this issue is present for every field that has no value. e.g. Radio-Button-Fields that nobody selected a value for.

**Comment by HQ063** [comment]
This is by design. Check `dynamic_entries` on README and use `:auto` or `update_dynamic_entry_cache!` if you prefer to always get all the fields.

**Comment by toadle** [comment]
@HQ063 Thanks for the heads-up. I also had to set `raise_for_empty_fields` to `false` to make this work as expected, but now it does!
