### ISSUE TITLE
Embedded Entry in Rich Text field

### ISSUE THREAD

**Issue by natematykiewicz** [contentful/contentful.rb#255]
I've got an Entity called "Article" that has Rich Text field called "Body", which I've Embedded in Entry into. I can't figure out how to find the contents of the embedded entry without doing extra web requests. When going through the rich text field in Ruby by using `Contentful::Client.new({}).entry(id).body`, I see:

```ruby
{
  "nodeType" => "document",
  "data" => {},
  "content" => [
    {
      "nodeType" => "embedded-entry-block",
      "data" => {
        "target" => {
          "sys" => {
            "id" => "MY-CONTENTFUL-ENTRY-ID", # <------ Embedded entry id
            "type" => "Link",
            "linkType" => "Entry"
          }
        }
      },
     "content" => []
    }
  ]
}
```

If I look at the JSON that was returned when requesting my Article, I notice there's this:

```json
{
  "includes": {
    "Entry": [
      {
        "metadata": {
          "tags": []
        },
        "sys": {
          "space": {
            "sys": {
              "type": "Link",
              "linkType": "Space",
              "id": "MY-SPACE-ID"
            }
          },
          "id": "THAT-SAME-EMBEDDED-ENTRY-ID", // <---- Same embedded entry id
          "type": "Entry",
          "createdAt": "2022-09-23T21:28:19.059Z",
          "updatedAt": "2022-09-23T21:28:19.059Z",
          "environment": {
            "sys": {
              "id": "master",
              "type": "Link",
              "linkType": "Environment"
            }
          },
          "revision": 1,
          "contentType": {
            "sys": {
              "type": "Link",
              "linkType": "ContentType",
              "id": "MY-CONTENT-TYPE"
            }
          },
          "locale": "en-US"
        },
        "fields": {
          "foo": 123, // <--- I'd love to access these fields when rendering the Article body
        }
      }
    ]
  }
}
```

How do I access this information within the Ruby code? It's worth noting that other included references work fine. This problem seems strictly about Embedded Entries in Rich Text fields.

**Comment by natematykiewicz** [comment]
I just spotted [this line](https://github.com/contentful/contentful.rb/blob/1f3d9a5fc99cf41a6130f97bcf651c4f64ba0b5c/spec/entry_spec.rb#L705), which showed me that this is supposed to work. I realized the problem is that it only links it in, if `dynamic_entries` is set to `:auto`, which I did not set because it fires off a 80ms `https://cdn.contentful.com/spaces/MY-SPACE-ID/environments/master/content_types?limit=1000`, API call per Contentful request, and I was doing 3 Contentful web requests in a single page. 240ms of overhead seemed like a lot, when all I though this option did was avoid method missing errors on nil values.

It feels like the Contentful gem could cache the content types within a single Rails web request.

Like if I do:

```
def show
  Contentful::Client.new.entry('something')
  Contentful::Client.new.entries('related-entries')
  Contentful::Client.new.entries('something else important')
end
```

This is 6 API calls. It feels like it could be 4 (3 `entries` and 1 `content_types`)

Also, is there a reason that it requires `dynamic_entries: :auto` to make that `target` be a `Contentful::Entry` instead of a string? It's already got the data loaded. It just needs to instantiate the entry instead of discarding the data it's already got.

**Comment by rubydog** [comment]
@natematykiewicz The 80ms call to `https://cdn.contentful.com/spaces/MY-SPACE-ID/environments/master/content_types?limit=1000` is only fired when a client is initialized. Ideally, you initialize the client once and reuse it to make further queries thus reducing multiple calls to `https://cdn.contentful.com/spaces/MY-SPACE-ID/environments/master/content_types?limit=1000`.

**Comment by natematykiewicz** [comment]
Oh, that actually helped me a lot! Thanks!
