### ISSUE TITLE
Can you please publish a new version to Ruby Gems?  (We're missing an important fix from master)

### ISSUE THREAD

**Issue by griff-stripe** [contentful/contentful.rb#258]
The last fix (https://github.com/contentful/contentful.rb/pull/235) is a huge performance boost, but the latest version (v2.16.3) does not include it.

**Comment by rubydog** [comment]
Will do.

**Comment by griff-stripe** [comment]
Thank you!

**Comment by rubydog** [comment]
New version is available at: https://rubygems.org/gems/contentful/versions/2.17.0
