### ISSUE TITLE
NoMethodError for several methods on Entry

### ISSUE THREAD

**Issue by nomasprime** [contentful/contentful.rb#263]
Things like `Entry.published_at` aren't working, raised `NoMethodError`.

**Comment by rubydog** [comment]
Hey @nomasprime, thanks for reporting the issue. I will take a look at it next and get back to you. Have a nice weekend.

Cheers
Bhushan

**Comment by rubydog** [comment]
Hey @nomasprime,

I'd appreciate it if you could provide more context regarding the issue you're experiencing. I attempted to access all the methods, including `updated_at`, on my end and didn't encounter any problems. From my understanding, there isn't a default `Entry.published_at`, but there is `Entry.updated_at`. You can refer to the documentation for more information: [Contentful Documentation - Date and Time Format](https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/date-and-time-format)

Cheers

**Comment by rubydog** [comment]
We're closing this issue for now as there hasn't been any activity in over 3 weeks. It doesn't seem to be related to the library itself. If you run into this issue again or have any related concerns, please feel free to reopen it. Thanks for your contributions!
