### ISSUE TITLE
Query to Display Category List and Linked Entries

### ISSUE THREAD

**Issue by thoughtandtheory** [contentful/contentful.rb#45]
So I have two different content_types:

Jobs
Departments

In Jobs, there is a link field to a single department. It's a required field so all jobs are associated to at least one department.

I'm trying to display a list of jobs by department:

Department
* Job
* Job

Department
* Job

...etc

I was searching through the documentation to see if there was any way to query the departments and then somehow join the jobs associated with that department.

**Comment by pxlpnk** [comment]
Unfortunately this is not yet possible, however you can include the linked departments in the query for the jobs and filter them on the client side:

```ruby
client.entries(content_type: 'job_content_type_id', include: 1)
```
Another way would be to rethink your content_model and link a department to a job, or create links in both directions.

**Comment by thoughtandtheory** [comment]
When you say filter them on the client side, how would that work?

As for doing it in both directions, I think it'd end up doubling up effort on the content team.

**Comment by grncdr** [comment]
To group the jobs by department on the client would look something like this:

```rb
client.entries(content_type: 'job_content_type_id', include: 1).group_by(&:department).each do |department, jobs|
  puts department.name
  jobs.each do |job|
    puts ' - ' + job.name
  end
end
```

The above code assumes that you are using [dynamic entries](https://github.com/contentful/contentful.rb#dynamic-entries) and both the Department and Job content types have a `name` field. You may need to adjust it to access departments via `entry.fields[:department]` and/or adjust the field names.

**Comment by pxlpnk** [comment]
@thoughtandtheory did this work for you? Can we close this ticket then?
