### ISSUE TITLE
Ruby client restricted to production token only (with a Limited Account)?

### ISSUE THREAD

**Issue by virtualandy** [contentful/contentful.rb#46]
Is the ruby client restricted to production only tokens? Note I'm on a Limited/Free account at the moment.

I can successfully hit our space and associated endpoints via curl using the "Preview" token. But when I do that via the ruby client I get ```"Contentful::Unauthorized: Contentful::Unauthorized"```.

Using the production token works fine. (I get a similar "Access Denied" error when trying to hit the API using the Preview token via [Postman, a Chrome extension](https://getpostman.com/).) 

Assuming this is known, just didn't see it documented and threw me for a loop a little bit. I probably just missed it. :) 

If I upgrade to a paid plan, does it remove this restriction (we want preview functionality for a 'staging' instance)?

**Comment by pxlpnk** [comment]
The client is capable of using the regular api and the preview api.
It is not documented in the readme, I will fix this ASAP.

Until then consult the documentation on our site: https://www.contentful.com/developers/documentation/content-delivery-api/ruby/#preview-api

To use the ruby client with the preview api you need to specify the host:

```ruby
client = Contentful::Client.new(
  host: 'preview.contentful.com',
  space: 'yourspace',
  access_token: 'yourtoken',
  dynamic_entries: 'auto'
)
```

Hope this helps

**Comment by virtualandy** [comment]
@pxlpnk Ah, totally missed that in the docs on contentful.com. Thanks, that should fix me up!

**Comment by virtualandy** [comment]
Hmmm. Tried this and still got unauthorized. 

If I use the production token (but the preview host) it works but only gives me the published entries.

Maybe I'm doing something wrong, though. I can send my space ID/token into support if that helps.

```
[14] pry(main)> preview_client = Contentful::Client.new(
[14] pry(main)*   host: 'preview.contentful.com',
[14] pry(main)*   space: ENV['CONTENTFUL_SPACE_ID'],
[14] pry(main)*   access_token: ENV['CONTENTFUL_PREVIEW_TOKEN'],
[14] pry(main)* dynamic_entries: :auto)
Contentful::Unauthorized: Contentful::Unauthorized
from .../gems/contentful-0.4.0/lib/contentful/client.rb:174:in `get'
```

**Comment by pxlpnk** [comment]
In your API key settings you can obtain your preview api token, this one is a different one from the production token. They both can *not* be used for the other API.
Also the API settings give you and example curl command and example ruby code that works.

If the problem continues please send your space id to support@contentful.com and we take a deeper look.

**Comment by virtualandy** [comment]
Just as follow up here, the key was to use the ```api_url:``` parameter, not ```host:``` :

```
2.1.2 :026 > client = Contentful::Client.new(
2.1.2 :027 >     api_url: 'preview.contentful.com',
2.1.2 :028 >       access_token: 'e5e8d4c5c122cf28fc1af3ff77d28bef78a3952957f15067bbc29f2f0dde0b50',
2.1.2 :029 >       space: 'cfexampleapi'
2.1.2 :030?>   )
```
This worked using the [demo space credentials](https://www.contentful.com/developers/documentation/content-delivery-api/ruby/#preview-api-usage) that's listed in the docs.

**Comment by pxlpnk** [comment]
Thank you for the update, I will add this to the readme right away!
