### ISSUE TITLE
VCR is throwing error while recording cassettes when used with http 0.7.1

### ISSUE THREAD

**Issue by charlieko** [contentful/contentful.rb#47]
I forked the repository to make a modified version suitable for my company to use. I realized that re-recording cassettes fails with the following error.

```
Failure/Error: vcr('content_type') { client.get(request) }
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./spec/support/vcr.rb:13:in `vcr'
     # ./spec/client_class_spec.rb:47:in `block (3 levels) in <top (required)>'
```

For this particular error, it's from client_class_spec, but all other specs threw the similar error.

I spent hours tracking where this is thrown and found out that it's from incompatibility between vcr 2.7.3 and http 0.7.1. Downgrading http to 0.6.0 fixed this problem, and I was able to re-record cassettes from the different end point we are using.

I do not know exactly why this error is thrown.

**Comment by pxlpnk** [comment]
Thank you for reporting this. 
Do you maybe have the code where the request object is built?

**Comment by charlieko** [comment]
The only change made to the request object is the uri. It is something like `'http://www.example.com:1337/spaces/asdf'` instead of the normal contentful uri with the default http port.

**Comment by pxlpnk** [comment]
I take a look at it in the next couple of days, are you using a caching proxy in between that modifies the data somehow? Why do you point it to a different URL?

**Comment by charlieko** [comment]
Can't really say in details since it's related to my company's service architecture, but it's kind of like what you said - proxy, but using the proxy option already provided does not work for a number of reasons. 

I also noticed that some of the example data that Contentful returns changed, so there are some tests that fail that presume a certain data to be returned from it after re-recording cassettes. It wasn't hard to fix those.

**Comment by pxlpnk** [comment]
Would it be ok for you to send an email to support@contentful.com I would like to learn more about how you use the gem.

Most of the data should not have changed, do you maybe have a list for me what you had to change?

As you pointed out pining the http version to `0.6.x` solves the issue, I still was not able to figure out why what causes the problem.

**Comment by pxlpnk** [comment]
I looked deeper into it, it seems to be that psych is related to the issue. It works good with the JSON format of VCR.

One "fix" would be to use the JSON format. Another would be to dig deeper and figure out what the problem with psych, http and vcr actually is.

**Comment by pxlpnk** [comment]
http.rb v.0.8.0 was just released and it seems to have fixed those issues. 
I tested it locally and the does not occur anymore.

https://github.com/httprb/http.rb/tree/v0.8.0
