### ISSUE TITLE
How to build a resource from a webhook callback?

### ISSUE THREAD

**Issue by edtjones** [contentful/contentful.rb#55]
Hi there

It would be really useful to build a resource (mapped to the correct class if there's a resource mapping for it) from the JSON returned by a callback. Can I instantiate at `Contentful::Response` with the content of the webhook? Or should I be higher up the stack, maybe building a separate class which includes `Contentful::Resource` ?

It would be really handy to be able to cache the object on callback.

(This is for https://github.com/errorstudio/contentful_rails)

Thanks.

**Comment by edtjones** [comment]
(Of course this presupposes that the contents of the webhook JSON match the JSON returned from a Contentful API request - I haven't checked.)

**Comment by pxlpnk** [comment]
In theory it would be possible. 
I made a tiny prototype once to see how this could work, but I encountered a few problems. One being that the Resource has more responsibilities as it should, which makes just parsing the response quite hard.
Simplifying the `Resource` class would be a first step so that JSON can be parsed at any time without the need of having a client object or others.

**Comment by edtjones** [comment]
Hi @pxlpnk  - closed because it's not on the roadmap? Might be nice to keep open but dormant somehow.

**Comment by pxlpnk** [comment]
At the current time there are no plans to support this.
To be able to support this we would need to remodel and detangle the `Resource` class quite a bit. 
In favour of simplicity there _could_ be a separate Gem handling this.

**Comment by neonichu** [comment]
FWIW, we have [this gist](https://gist.github.com/neonichu/17a987aeeb256d4bf6f3) with a stopgap workaround

**Comment by edtjones** [comment]
Thanks @neonichu @pxlpnk - will investigate options if we need this on the next project we work on.

**Comment by pxlpnk** [comment]
@neonichu we could add this code to the README maybe. That would be a first step into the right direction.
