### ISSUE TITLE
NoMethodError when creating custom class with Contentful::Resource

### ISSUE THREAD

**Issue by toadle** [contentful/contentful.rb#69]
Hey guys, 

too bad that the documentation for creating custom classes is a little sparse, but I'm trying to follow the instructions in https://github.com/contentful/contentful.rb/blob/master/examples/custom_classes.rb . Where it says that any custom class just needs to include `Contentful::Resource`. Sadly is is not stated how to use the "property"-stuff so I might be doing something wrong. 

I'm trying to create a custom class for articles. It works like this: 

```
class Contentful::Article < Contentful::Entry
...
   def entries
      <does fetching>
   end
end
```

Which works: 
```
[1] pry(main)> Contentful::Article.entries
=> #<Contentful::Array: @properties={:total=>2, :limit=>100, :skip=>0, :items=>[#<Contentful::Article: @fields={:slug=>...............
```

But doing it this way makes it very hard to write test, cause I can't create `Contentful::Article`s with a factory. 

So I tried
```
class Contentful::BaseEntry
  include Contentful::Resource

  property :fields
...
end
```

But this gives me:
```
[2] pry(main)> Contentful::Article.entries.first
NoMethodError: undefined method `[]=' for nil:NilClass
from /Users/tim/.rvm/gems/ruby-2.2.2@hopla/gems/contentful-0.5.0/lib/contentful/resource_builder.rb:182:in `block (2 levels) in replace_children'
```

Whenever I try to fetch something. 

Any thoughts?

**Comment by toadle** [comment]
@contributors Any advice?

**Comment by dlitvakb** [comment]
Hey @toadle,

Thanks for your question, I'll take a look at it and get back to you shortly.

**Comment by dlitvakb** [comment]
Hey @toadle,

You can follow this example, let me know if it's of any help:

```ruby
require 'contentful'

module TestHelper
  def client(access_token, space_id)
    @client ||= Contentful::Client.new(
      access_token: access_token,
      space: space_id,
      dynamic_entries: :auto,
      raise_errors: true,
      entry_mapping: {
        'YOUR_ARTICLE_CONTENT_TYPE_ID_HERE' => Contentful::Article
      }
    )
  end
end

class Contentful::Article < Contentful::Entry
end

c = client(ENV['CDA_TOKEN'], ENV['ARTICLE_SPACE'])
articles = c.entries(content_type: 'YOUR_ARTICLE_CONTENT_TYPE_ID')
```

The result of that should be something like the following:

```ruby
[2] pry(main)> c.entries(content_type: '3dKVHO6T9SwWWiesOCou6k')
=> #<Contentful::Array: @properties={:total=>1, :limit=>100, :skip=>0, :items=>[#<Contentful::Article: @fields={:name=>"Article 1", :content=>"something"} @sys={:space=>#<Contentful::Link: @sys={:type=>"Link", :linkType=>"Space", :id=>"wio7th6i1n7o"}>, :type=>"Entry", :contentType=>#<Contentful::Link: @sys={:type=>"Link", :linkType=>"ContentType", :id=>"3dKVHO6T9SwWWiesOCou6k"}>, :id=>"19JizQmHlUiwcqe24ekk0q", :revision=>1, :createdAt=>#<DateTime: 2015-10-23T10:28:11+00:00 ((2457319j,37691s,510000000n),+0s,2299161j)>, :updatedAt=>#<DateTime: 2015-10-23T10:28:11+00:00 ((2457319j,37691s,510000000n),+0s,2299161j)>, :locale=>"en-US"}>]} @sys={:type=>"Array"}>
```

Please let me know if this helps you.

**Comment by toadle** [comment]
@dlitvakb Thanks, for the answer. The content-mapping thing is not really my problem. That is working without a problem. 

My basic problem is to create the classes that I can insert into the content-mapping. I got factories for my tests working, by just doing this: 

```
FactoryGirl.define do
  factory :article, class: Contentful::Article do
    title             { FFaker::DizzleIpsum.word }
    slug              { FFaker::DizzleIpsum.word.gsub(" ", "_").underscore }
    content           { FFaker::Lorem.paragraphs(3).join('\n') }
    category          { build(:category) }
    authors           { [build(:author)] }
    sources           { FFaker::Lorem.paragraphs(1).first }
    teaser_image      { build(:image) }

    initialize_with { new({}) }

    trait :with_image_gallery do
      image_gallery   { build(:image_gallery) }
    end
  end
end
```

But I have to hack it with `initialize_with` otherwise it raises errors. 

The basic question is, if the description in https://github.com/contentful/contentful.rb/blob/master/examples/custom_classes.rb does indeed work. 

Shoud it be enough to include `include Contentful::Resource` in your class to make it work as a content-mapping (which would be great) or do you have to extend `Contentful::Entry`?

**Comment by dlitvakb** [comment]
@toadle if you take a look at the constructor for [`Contentful::Resource`](https://github.com/contentful/contentful.rb/blob/master/lib/contentful/resource.rb#L24), it is expecting a JSON object with an API-like formatted input.

I'll look into adding an empty default, as it seems that this is actually the expected behavior.

**Comment by toadle** [comment]
@dlitvakb Thanks!
In my experience just including the `Contentful::Resource` module in any content-mapping-class is not enough and will result in the exception shown in my first post. There must be some dependency to `Contentful::Entry` which makes inheritance necessary.

Perhaps you could check that too. Otherwise

```
class Contentful::Article
  include Contentful::Resource
end
```

will not work, but

```
class Contentful::Article < Contentful::Entry
end
```

will.

**Comment by dlitvakb** [comment]
@toadle 

After merging #71 your issue will be resolved

**Comment by toadle** [comment]
@dlitvakb Cool, thanks!
