### ISSUE TITLE
Contentful::Entry-objects not dumpable

### ISSUE THREAD

**Issue by toadle** [contentful/contentful.rb#80]
Hey guys, 

I'm sorry to bother you with another thing, but this is just the stuff coming up while working on our project. 

I've been trying to **cache** certain objects retrieved with `contentful.rb` in order to make certain requests not hit the API all the time. Makes page-loads faster. 

Therefore I wanted to put a `Contentful::Category < Contentful::Entry`-object into the Rails-Cache. In this process the objects gets `Marshal.dump`ed.

Doing that reveals that somewhere inside the object there must be a `Proc` assigned, because: 

```
Marshal.dump client.entries({"content_type" => "<some entry-id>"}).first
TypeError: no _dump_data is defined for class Proc
from (pry):4:in `dump'
```

I can't figure out where, cause I already tried writing my own `marshal_dump` / `marshal_load`-methods. 

During testing I noticed that everything that https://github.com/errorstudio/contentful_model hands out, is cachable without problems.

Any hints?

**Comment by dlitvakb** [comment]
Hey @toadle,

Thanks for the input,

I've never personally tried to do such thing, so haven't come up with it.

I'll be looking into what's going on and how to fix it.

**Comment by dlitvakb** [comment]
Hey @toadle,

I've just finished the PR that covers #79 and this issue.

We'll be merging this soon and getting a new release.

Until then, can you try using this branch and see if it covers your needs?

Please let me know if you need any further help.

**Comment by toadle** [comment]
@dlitvakb Thanks for working on this so fast. 
We just started a new sprint yesterday and left this out intentionally. But I'll figure this in and give you feedback!

**Comment by toadle** [comment]
@dlitvakb I directly commented on https://github.com/contentful/contentful.rb/pull/81 .
