### ISSUE TITLE
Link Not Resolving

### ISSUE THREAD

**Issue by lpender** [contentful/contentful.rb#82]
Wondering if you could double check that the gem is resolving `link`s for you correctly?

Here is the output of the object I am trying to resolve...

```
#<Contentful::Link: @sys={:type=>"Link", :linkType=>"Asset", :id=>"5GLKTXSlBSUqKUYCqYa8Y4"}>
```

Here is the link source I believe it should correctly resolve to:

```
https://images.contentful.com/li3hk7u6wodg/dECFlgwAq4omSMciO06AI/2fe9b094a4e22a915b1b5a5b82ff8a9c/anovelromance-1211.jpg
```

Here is the error:

```
Contentful::NotFound (The resource could not be found.)
```

Thanks!

**Comment by dlitvakb** [comment]
Hey @lpender,

I'll be looking into this.

As for the image that should be displayed, it does not have the same ID as the asset you're saying that the link does not work for:

```diff
-"dECFlgwAq4omSMciO06AI"
+"5GLKTXSlBSUqKUYCqYa8Y4"
```

Please verify that the asset corresponding to that ID is correctly Published and not in Draft mode

I'll still be looking if this is possible for other cases

**Comment by lpender** [comment]
Maybe it's a caching issue? It's the only image I have published.

**Comment by lpender** [comment]
I'm getting a totally different response today from the same set of code. 

```
#<Contentful::Asset: @fields={:title=>"Chillness", :file=>#<Contentful::File: @properties={:fileName=>"anovelromance-1211.jpg", :contentType=>"image/jpeg", :details=>{"image"=>{"width"=>900, "height"=>600}, "size"=>1533474}, :url=>"//images.contentful.com/li3hk7u6wodg/dECFlgwAq4omSMciO06AI/2fe9b094a4e22a915b1b5a5b82ff8a9c/anovelromance-1211.jpg"}>} @sys={:space=>#<Contentful::Link: @sys={:type=>"Link", :linkType=>"Space", :id=>"li3hk7u6wodg"}>, :type=>"Asset", :id=>"dECFlgwAq4omSMciO06AI", :revision=>1, :createdAt=>Tue, 08 Dec 2015 19:40:12 +0000, :updatedAt=>Tue, 08 Dec 2015 19:40:12 +0000, :locale=>"en-US"}>
```

Not sure how that happened but this appears to have a URL that I can work with.

Thanks!

**Comment by dlitvakb** [comment]
Hey @lpender,

No problem!

Sometimes the Image API takes a bit longer to update as there is a Processing job in the background. Also CDN Caches sometimes have a bit of a delay when cleaning the cache after an update.

Cheers
