### ISSUE TITLE
Progressive image loading unavailable

### ISSUE THREAD

**Issue by cabouffard** [contentful/contentful.rb#86]
Hi!

As per the [documentation][1], it seems like we should be able to send the flag `fl: progressive` to the api in order to retrieve a JPEG Progressive image. 

When I look in the code from this gem, it seems like this key is not available and is being thrown out. I was wondering if this behavior was intended or if it is a mistake.

https://github.com/contentful/contentful.rb/blob/master/lib/contentful/asset.rb

Thank you, have a nice day!

[1]: https://jsapi.apiary.io/apis/contentfulimagesapi/reference/changing-formats/progressive-jpegs/retrieve-an-image.html

**Comment by dlitvakb** [comment]
Hey @cabouffard,

We're looking into this,

Looks like the `#image_url` helper doesn't include that parameter, I'm talking with the API team on how it's best to include it.

In the meantime you can append it in your presentation layer.

Hope this helps,

Cheers
