### ISSUE TITLE
Issue in Middleman 4.0.0

### ISSUE THREAD

**Issue by aaromnido** [contentful/contentful.rb#92]
Hi guys,

**I'm trying to test your "contentful_middleman" extension in a MD 4.0.0 site.**

**I applied this in my Gemfile:**
gem "contentful_middleman"

**Then, "bundle install" an the shel (OS X terminal) rise next error:**
Bundler could not find compatible versions for gem "middleman-core":
  In Gemfile:
    contentful_middleman was resolved to 0.0.4, which depends on
      middleman-core (~> 3.3)

    middleman (>= 4.0.0) was resolved to 4.0.0, which depends on
      middleman-core (= 4.0.0)

**What is going wrong?**

**Comment by dlitvakb** [comment]
Hey @aaromnido,

For Middleman V4 projects, you need to enter the following in your Gemfile:

```ruby
gem "contentful_middleman", git: 'git@github.com:contentful/contentful_middleman.git', branch: 'dl/upgrade-to-v4'
```

For Middleman V3 projects, the correct `contentful_middleman` version is `'~> 1.3'`

Hope that helps,

Cheers

**Comment by aaromnido** [comment]
Thanks ;-)

**Comment by lukewduncan** [comment]
Praise the lord. Was looking for a fix for this. Thanks!
