### ISSUE TITLE
The sync method is throwing "undefined method 'next_sync_url'"

### ISSUE THREAD

**Issue by cabouffard** [contentful/contentful.rb#93]
Hi!

The sync method as started to fail for us. We are getting the following error:
`NoMethodError: undefined method 'next_sync_url' for #<Array:0x007f9955b2a408>` from `lib/contentful/sync.rb:82`

Here is how we are calling the sync
```
sync = contentful.client.sync(initial: true, type: 'Entry')
sync.each_item do |item|
    # Do stuff here.
end
```
Where contentful is an instance of `Contentful::Client` object. 

We run this task at least twice per day and it only started to fail today. Is there anything that has changed from the API? 

The `page` value that is currently pass by parameter to `update_sync_state_from!` is an array that contains multiple type of entries, with only 100 entries at a time.

I am unsure how I can fix that problem. It seems like the type of object returned is different than what it used to be from your API.

Thank you!
Have a nice day!

**Comment by cabouffard** [comment]
Hey! 

Any update on this? Can I provide you additional informations?

Thanks!

**Comment by dlitvakb** [comment]
Hey @cabouffard,

I'll be looking into it.

One thing, the method `:each_time` doesn't exist, are you using `:each_item`??

I'll also escalate this to the API Team, as I saw a similar issue a while ago that was unrelated to the gem.

I'll get back to you shortly

**Comment by cabouffard** [comment]
@dlitvakb My apologies, you're right, I meant `:each_item`. 

Thanks a lot!

**Comment by dlitvakb** [comment]
Hey @cabouffard,

I just tried running a Sync call with a Space with over 500 entries, and ran successfully with no error.

Could you provide some more context?

Which version of the gem are you using?

How do you initialize your client?

Cheers

**Comment by cabouffard** [comment]
Here is how I initialize the client
```
    @client ||= begin
      client = Contentful::Client.new(
        access_token: access_token,
        space: space_id,
        api_url: api_url,
        entry_mapping: # Custom Entry Mapping Here,
        logger: Rails.logger
      )
    end
```

`@client.sync(initial: true, type: 'Entry').each_item`
^ This returns me an array of 100 items then crashes with the following stack trace

```
NoMethodError: undefined method `next_sync_url' for #<Array:0x007facad5719d8>
/opt/rubies/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/contentful.rb-82950e733e3e/lib/contentful/sync.rb:82:in `update_sync_state_from!'
/opt/rubies/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/contentful.rb-82950e733e3e/lib/contentful/sync.rb:65:in `get'
/opt/rubies/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/contentful.rb-82950e733e3e/lib/contentful/sync.rb:37:in `first_page'
/opt/rubies/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/contentful.rb-82950e733e3e/lib/contentful/sync.rb:24:in `each_page'
/opt/rubies/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/contentful.rb-82950e733e3e/lib/contentful/sync.rb:53:in `each_item'
```

As you can see I am the version `0.10.0` at `https://github.com/contentful/contentful.rb/commit/82950e733e3e972de6413345282d1cbae1467838`

I tried doing the following code above in a Rails Console and I was getting the stack trace above.

If you need additional information, don't hesitate!

**Comment by dlitvakb** [comment]
Hey @cabouffard,

I'm curious about 2 things that might be what's breaking this,

What's the custom mapping? If it is a proxy, there are specific proxy parameters.

Cheers

**Comment by cabouffard** [comment]
@dlitvakb 
Hey! My custom entry mapping is something similar of what the gem documentation says:

```
  entry_mapping: {
    'cat' => Cat
  }
```
But I use the ID provided by Contentful and our own Class.

We are not using Proxy of any kind. Also, this errors started happening last week, and prior to that everything was working fine. Our implementation hasn't changed since then, which is what I find really weird.

**Comment by dlitvakb** [comment]
Hmm, could you insert a debugger, and check if that array that's appearing there is a `Contentful::Array` or an `::Array`??

Maybe something having to do with the custom mapping is making it not able to resolve to the proper class

**Comment by cabouffard** [comment]
You're right, disabling `entry_mappings` made the behavior return to its correct state. I am not being returned a `#<Contentful::SyncPage:0x3fd705efc434>` instead of an `::Array`

Sooo weird. I'll investigate further see if I can figure out what the problem is!

Thank you for suggesting that!

**Comment by dlitvakb** [comment]
No problem, please let me know if you continue seeing a weird behavior.

**Comment by cabouffard** [comment]
Problem solved, we were overwriting the `request.get` method to always return `request.get.items`, which in that case was an array. 

The problem was not happening when directly assigning a hash to the `entry_mapping` field, but it was happening when we were assigning a method that would return a hash to the `entry_mapping`. 

Overwriting the method caused a bunch of ghost issues! 
Thank you for you time.

Have a nice day!

**Comment by dlitvakb** [comment]
No problem! Glad you worked it out

Cheers
